export const TOGGLE_FLASH = 'camera/TOGGLE_FLASH'
export const CHANGE_CAMERA = 'camera/CHANGE_CAMERA'
export const SAVE_PICTURE = 'camera/SAVE_PICTURE'
export const SAVE_TO_GALLERY = 'camera/SAVE_TO_GALLERY'
export const SAVE_CUSTOMIZED_PICTURE = 'camera/SAVE_CUSTOMIZED_PICTURE'

export default {
  TOGGLE_FLASH,
  SAVE_PICTURE,
  CHANGE_CAMERA,
  SAVE_TO_GALLERY,
  SAVE_CUSTOMIZED_PICTURE,
}
