export const ADD_STICKER = 'stickers/ADD_STICKER'
export const SELECT_STICKER = 'stickers/SELECT_STICKER'
export const REMOVE_STICKER = 'stickers/REMOVE_STICKER'
export const UNSELECT_STICKER = 'stickers/UNSELECT_STICKER'
export const CLEAN_USED_STICKERS = 'stickers/CLEAN_USED_STICKERS'
export const UPDATE_STICKER_POSITION = 'stickers/UPDATE_STICKER_POSITION'
export const FILTER_STICKER = 'stickers/FILTER_STICKER'

export default {
  ADD_STICKER,
  SELECT_STICKER,
  REMOVE_STICKER,
  FILTER_STICKER,
  UNSELECT_STICKER,
  CLEAN_USED_STICKERS,
  UPDATE_STICKER_POSITION,
}
