export const STICKERS_MODAL = 'STICKERS_MODAL'
export const TAKE_PHOTO_SCREEN = 'TAKE_PHOTO_SCREEN'
export const CUSTOMIZE_PHOTO_SCREEN = 'CUSTOMIZE_PHOTO_SCREEN'

export default {
  STICKERS_MODAL,
  TAKE_PHOTO_SCREEN,
  CUSTOMIZE_PHOTO_SCREEN,
}
